/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Acoes;

import controle.SuporteIntercorrenciaJpaController;
import controle.SuportePontoeletronicoJpaController;
import controle.SuporteUsuariosJpaController;
import entidades.SuporteIntercorrencia;
import entidades.SuportePontoeletronico;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Hilton
 */
public class ForaDoHorario extends javax.swing.JDialog {

    private final SuportePontoeletronicoJpaController emfAcesso = new SuportePontoeletronicoJpaController(new util.Persistencia().emf());
    private final SuporteIntercorrenciaJpaController emfInter = new SuporteIntercorrenciaJpaController(new util.Persistencia().emf());
    private final SuporteUsuariosJpaController emfUsuario = new SuporteUsuariosJpaController(new util.Persistencia().emf());
    private Date dtGravada;
    private Date dtAtual;
    private int i_ponto;
    private String nome_usuario;
    public String gravar = "nao";
    public String motivo = "";
    private int entrada = 0;
    private int caracteresMotivo = 10;///*//

    public ForaDoHorario(java.awt.Frame parent, boolean modal, int i_ponto, String usuario, Date dtGravada, Date dtAtual) {
        super(parent, modal);
        initComponents();
        this.dtAtual = dtAtual;
        this.dtGravada = dtGravada;
        this.i_ponto = i_ponto;
        this.nome_usuario = usuario;
        jSinicio.setValue(dtGravada);
        jSfim.setValue(dtAtual);
        jLusuarioNome.setText(this.nome_usuario);
        if (i_ponto != 0) {
            jLiUsuario.setText(String.valueOf(emfAcesso.findSuportePontoeletronico(i_ponto).getIUsuario().getIUsuario()));
        }
    }

    public ForaDoHorario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.entrada = 1;
    }

    public String formato(Date dt, String tipo) {
        SimpleDateFormat formato = new SimpleDateFormat(tipo);
        return formato.format(dt);
    }

    public String gravado() {
        int caracteres = jTAmotivo.getText().trim().getBytes().length;
        if (caracteres < caracteresMotivo) {
            this.gravar = "nao";
            JOptionPane.showMessageDialog(null, "Motivo muito curto!\nDigite mais '" + (caracteresMotivo - caracteres) + "' caracteres", "Registro não gravado", JOptionPane.INFORMATION_MESSAGE);
            jTAmotivo.requestFocus();
            return this.gravar;
        } else {
            if (entrada == 0) {
                Date dtInicio = (Date) jSinicio.getValue();
                Date dtFim = (Date) jSfim.getValue();
                String mask = "dd/MM HH:mm";
                String sit = "ATRASO -  Hora informada: " + formato(dtInicio, mask) + " | Hora do registro: " + formato(dtFim, mask);
                SuporteIntercorrencia inter = new SuporteIntercorrencia();
                inter.setIPonto(emfAcesso.findSuportePontoeletronico(this.i_ponto));
                inter.setDtInicio(dtInicio);
                inter.setDtFim(dtFim);
                inter.setMotivo(jTAmotivo.getText().trim());
                inter.setSituacao(sit);
                inter.setAlteracao(this.nome_usuario);
                emfInter.create(inter);
                emfInter.getEntityManager().close();
                JOptionPane.showMessageDialog(null, "Registro gravado com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
                this.gravar = "atraso";
                this.dispose();
                return this.gravar;
            } else {
                this.motivo = jTAmotivo.getText();
                this.gravar = "atraso";
                this.dispose();
                return this.gravar;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTAmotivo = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jSfim = new javax.swing.JSpinner();
        jSinicio = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBgravar = new javax.swing.JButton();
        jLiUsuario = new javax.swing.JLabel();
        jLusuarioNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro fora do horário");
        setResizable(false);

        jTAmotivo.setColumns(20);
        jTAmotivo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTAmotivo.setLineWrap(true);
        jTAmotivo.setRows(1);
        jTAmotivo.setWrapStyleWord(true);
        jTAmotivo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Motivo"));
        jTAmotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTAmotivoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTAmotivo);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSfim.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jSfim.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        jSfim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSfim.setEditor(new javax.swing.JSpinner.DateEditor(jSfim, "HH:mm"));
        jSfim.setEnabled(false);
        jSfim.setMaximumSize(new java.awt.Dimension(144, 64));
        jSfim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSfimStateChanged(evt);
            }
        });
        jSfim.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jSfimInputMethodTextChanged(evt);
            }
        });

        jSinicio.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jSinicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        jSinicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSinicio.setEditor(new javax.swing.JSpinner.DateEditor(jSinicio, "HH:mm"));
        jSinicio.setEnabled(false);
        jSinicio.setMaximumSize(new java.awt.Dimension(144, 64));
        jSinicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSinicioStateChanged(evt);
            }
        });
        jSinicio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jSinicioInputMethodTextChanged(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hora informada:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hora do registro:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSfim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSfim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBgravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add_16.png"))); // NOI18N
        jBgravar.setText("GRAVAR REGISTRO");
        jBgravar.setEnabled(false);
        jBgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgravarActionPerformed(evt);
            }
        });

        jLiUsuario.setText("1");

        jLusuarioNome.setText("???");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBgravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLiUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jLusuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLiUsuario)
                    .addComponent(jLusuarioNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(310, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgravarActionPerformed
        gravado();
    }//GEN-LAST:event_jBgravarActionPerformed

    private void jSfimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSfimStateChanged

    }//GEN-LAST:event_jSfimStateChanged

    private void jSfimInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSfimInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSfimInputMethodTextChanged

    private void jSinicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSinicioStateChanged

    }//GEN-LAST:event_jSinicioStateChanged

    private void jSinicioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSinicioInputMethodTextChanged

    }//GEN-LAST:event_jSinicioInputMethodTextChanged

    private void jTAmotivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAmotivoKeyReleased
        int i = jTAmotivo.getText().trim().getBytes().length;
        if (i >= caracteresMotivo) {
            jTAmotivo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Motivo"));
            jBgravar.setEnabled(true);
        } else {
            jTAmotivo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Motivo (informe no mínimo mais " + (caracteresMotivo - i) + " caracteres)"));
            jBgravar.setEnabled(false);
        }
    }//GEN-LAST:event_jTAmotivoKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBgravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLiUsuario;
    private javax.swing.JLabel jLusuarioNome;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSfim;
    private javax.swing.JSpinner jSinicio;
    private javax.swing.JTextArea jTAmotivo;
    // End of variables declaration//GEN-END:variables
}
