/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Acoes;

import java.awt.Toolkit;
import java.io.File;

/**
 *
 * @author Hilton
 */
public class SelecionarArquivo extends javax.swing.JDialog {

    public File file;
    
    public SelecionarArquivo(java.awt.Frame parent, boolean modal, String tipo, String nome) {
        super(parent, modal);
        initComponents();
        switch (tipo){
            case "anexar":
                break;
            case "selecionar":
                jFCarquivo.setApproveButtonText("Selecionar");
                setTitle("Selecione o local para gravar o arquivo");
                jFCarquivo.setSelectedFile(new java.io.File(nome));
                break;
            case "navegador":
                setTitle("Selecione o executavel do navegador");
                jFCarquivo.setCurrentDirectory(new java.io.File("C:\\Program Files"));
                jFCarquivo.setApproveButtonText("Selecioar");
                break;
        }
        //this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone_2_24.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFCarquivo = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Arquivo");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(550, 373));

        jFCarquivo.setApproveButtonText("Anexar");
        jFCarquivo.setApproveButtonToolTipText("");
        jFCarquivo.setCurrentDirectory(new java.io.File("C:\\"));
            jFCarquivo.setDialogTitle("Selecione o arquivo");
            jFCarquivo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jFCarquivoActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFCarquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFCarquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            );

            setSize(new java.awt.Dimension(559, 411));
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jFCarquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCarquivoActionPerformed
        this.file = jFCarquivo.getSelectedFile();
        this.dispose();
    }//GEN-LAST:event_jFCarquivoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SelecionarArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SelecionarArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SelecionarArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SelecionarArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SelecionarArquivo dialog = new SelecionarArquivo(new javax.swing.JFrame(), true, "","");
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFCarquivo;
    // End of variables declaration//GEN-END:variables
}
